config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'skills#index'

  resources :skills do
    resources :projects
  end

  resources :projects, only:[:index]
  resources :users
  resources :posts do
    resources :comments
  end

  resources :references
  resources :recommendations

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects

  validates_presence_of :name
  validates_presence_of :description
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

def index
  @users = User.all()
  @skills = Skill.all()
end

def new
  @skill = Skill.new()
end

def create
  @skill = Skill.new(skill_params)
  if @skill.save
    flash[:notice] = "You've added a skill!"
    redirect_to root_path
  else
    flash[:alert] = "Oops! Try Again"
    render :new
  end
end

def show
  @skill = Skill.find(params[:id])
end

def edit
  @skill = Skill.find(params[:id])
end

def update
  @skill = Skill.find(params[:id])
  if @skill.update(skill_params)
    flash[:notice] = "You've edited" + " " + @skill.name
    redirect_to skill_path(@skill)
  else
    render :edit
  end
end

def destroy
  @skill = Skill.find(params[:id])
  @skill.projects.each do |project|
    project.destroy()
  end
  @skill.destroy()
  redirect_to root_path
end

private
  def skill_params
    params.require(:skill).permit(:name, :description)
  end

end

app/views/skills/_form.html.erb
<%= form_for object do |f| %>
  <div class="form-group">
    <%= f.text_field :name, :placeholder => "Skill Name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, :placeholder => "Description" %>
  </div>
  <%= f.submit :class => 'btn btn-warning' %>
<% end %>

<%= render 'layouts/errors', :object => object %>

app/views/skills/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
    <div class="row">
      <div class="col-sm-6">
        <h2>Edit <%=@skill.name%></h2>
      </div>
      <div class="col-sm-6">
        <%= render 'form', :object => @skill%>
      </div>
    </div>
  <% else %>
    <h5>Sorry, Permission Denied.</h5>
  <% end %>
<% else %>
  <h5>Please Login</h5>
<% end %>

app/views/skills/index.html.erb
<% @users.each do |profile| %>
  <% if profile.admin %>
    <div class="row">
      <div class="col-sm-8">
        <div class="profile profile-name">
          <h1><%= profile.name %></h1>
        </div>

        <div class="profile profile-email">
          <%= mail_to profile.email %>
        </div>

        <div class="profile profile-description">
          <%= profile.description %>
        </div>
        <div class="profile profile-linkedin">
          <%= link_to image_tag('http://uploads.strikinglycdn.com/page/images/icons/linkedin-icon.png'), profile.linkedin, :class => 'linkedin-link' %>
        </div>
        <div class="profile profile-github">
          <%= link_to image_tag('http://mihai-varga.github.io/theme/images/github.png'), profile.github, :class => 'github-link'%>
        </div>
    </div>
      <div class="col-sm-4 profile-col-2">
        <% if profile.image %>
          <%= image_tag (profile.image), class:'profile profile-image home-image' %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <h3>What I can do...</h3>
  <% @skills.each do |skill| %>
      <div class="well col-sm-3 skill-name">
        <%= link_to skill.name, skill_path(skill) %>
      </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-6 centered-col">
    <h3><%= link_to 'References', references_path, remote: true, class:'references'%></h3>
    <div class="references-div"></div>
  </div>

  <div class="col-sm-6 centered-col">
    <h3><%= link_to 'Recommendations', recommendations_path, remote: true, class:'recommendations'%></h3>
    <div class="recommendations-div">
    </div>
  </div>
</div>

app/views/skills/new.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
    <div class="row">
      <div class="col-sm-6">
        <h2>Show off your skills!</h2>
        <h5>Add a skill and watch them populate your homepage</h5>

      </div>
      <div class="col-sm-6">
        <%= render 'form', :object => @skill%>
      </div>
    </div>
  <% else %>
    <h5>Permission Denied, sorry!</h5>
  <% end %>
<% else %>
    <h5> Please Login. </h5>
<% end %>

app/views/skills/show.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
  <div class="row">
    <div class=" well col-sm-12 secondary-nav edit-delete-skill">
      <%= link_to 'Add Project', new_skill_project_path(@skill, @project) %> |
      <%= link_to 'Edit Skill', edit_skill_path(@skill) %> |
      <%= link_to 'Delete Skill', skill_path(@skill),
                                  :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %>
    </div>
  </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-sm-7">
    <h1><%= @skill.name %></h1>
    <div class="skill-description">
      <%= @skill.description %>
    </div>
  </div>
  <div class="col-sm-5 projects">
    <% if @skill.projects.any? %>
      <h3><%= @skill.name %> Projects</h3>
      <% @skill.projects.each do |project| %>
        <div class="project project-name">
          <img class="thumbnail" src="<%=project.image_url%>" />
          <%= link_to project.name, skill_project_path(@skill, project) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>