config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'skills#index'

  resources :skills do
    resources :projects
  end

  resources :projects, only:[:index]
  resources :users
  resources :posts do
    resources :comments
  end

  resources :references
  resources :recommendations

end

app/models/reference.rb
class Reference < ActiveRecord::Base

validates_presence_of :employer
validates_presence_of :name
validates_presence_of :phone
validates_presence_of :address
validates_presence_of :email
validates_presence_of :job_title



end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

  def index
    @references = Reference.all
  end

  def new
    @reference = Reference.new
  end

  def create
    @references = Reference.all
    @reference = Reference.new(reference_params)
    if @reference.save
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end
    end
  end

  private
    def reference_params
      params.require(:reference).permit(:name, :email, :address, :phone, :job_title, :employer)
    end

end

app/views/references/_form.html.erb
<%= form_for @reference, remote: true do |f| %>
<div class="form-group">
<%= f.text_field :name, placeholder: "Name" %>
</div>
<div class="form-group">
<%= f.text_field :phone, placeholder: "Phone" %>
</div>
<div class="form-group">
<%= f.text_field :address, placeholder: "Address" %>
</div>
<div class="form-group">
<%= f.text_field :employer, placeholder: "Employer" %>
</div>
<div class="form-group">
<%= f.text_field :job_title, placeholder: "Job Title" %>
</div>
<div class="form-group">
<%= f.text_field :email, placeholder: "Email" %>
</div>
<div class="form-group">
<%= f.submit class:'btn btn-success' %>
<% end %>

app/views/references/_refs.html.erb
<%= link_to "add your reference", new_reference_path, class:'add-ref', remote: true %>
<% if @references.any? %>
  <h3>References</h3>

  <% @references.each do |ref|%>
    <ul class="list-unstyled well">
      <li><h3><%= ref.name %></h3></li>
      <li><h5><%= ref.job_title %>, <%= ref.employer %></h5></li>
      <li><h5><%= ref.email %></h5></li>
      <li><h5><%= ref.phone %></h5></li>
      <li><h5><%= ref.address %></h5></li>
    </ul>
  <% end %>
<% else %>
  <h5>Check Back Soon!</h5>
<% end %>

app/views/references/create.js.erb
$('form').hide()
$(".references-div").html('<%= j render("refs") %>');
$(".add-ref").show()

app/views/references/index.js.erb
$('.hide-references').show;
$('.references').hide().after('<%= j render("refs") %>')

app/views/references/new.js.erb
$('.add-ref').hide().after("<%= j render('form')%>")