config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'skills#index'

  resources :skills do
    resources :projects
  end

  resources :projects, only:[:index]
  resources :users
  resources :posts do
    resources :comments
  end

  resources :references
  resources :recommendations

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of(:title)
  validates_presence_of(:content)
  has_many(:comments)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
    if params[:request_type] == "Show"
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js {render 'show'}
      end
    end
    if params[:request_type] == "Hide"
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js {render 'hide'}
      end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "New Post Created!"
      redirect_to posts_path
    else
      flash[:alert] = "Sorry, try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You successfully edited the post titled: " + @post.title
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/views/posts/_form.html.erb
<%= form_for object do |f| %>
  <div class="form-group">
    <%= f.text_field :title, :placeholder => "Post Title" %>
  </div>
  <div class="form-group">
    <%= f.text_field :content, :placeholder => "Post Content" %>
  </div>
  <div class="form-group">
    <%= f.text_field :image, :placeholder => "Image URL" %>
  </div>
  <%= f.submit :class => 'btn btn-warning' %>
<% end %>

<%= render 'layouts/errors', :object => object %>

app/views/posts/_post_list.html.erb
<% if @posts.any? %>

  <% @posts.each do |post| %>

    <div class="post well post-header">
      <%= post.created_at.to_date.strftime('%A')%>
      <%=post.created_at.to_date.strftime('%B')%>
      <%=post.created_at.to_date.strftime('%d')%>,
      <%=post.created_at.to_date.strftime('%Y') %>
      <div class="post post-updated-at">

        <% if post.created_at != post.updated_at %>
          <em>Updated <%= post.updated_at.to_date.strftime('%A')%>
          <%=post.updated_at.to_date.strftime('%B')%>
          <%=post.updated_at.to_date.strftime('%d')%>,
          <%=post.updated_at.to_date.strftime('%Y') %></em>
        <% end %>

      </div>
      <h3><%= post.title %></h3>
      <div class="well post">
        <% if post.image != nil %>
          <img class="post post-image" src="<%=post.image%>" />
        <% end %>
        <div class="post-content">
          <%= post.content %>
        </div>
      </div>
      <% if post.comments.any? %>
        <%= link_to post.comments.length.to_s + " Comments", posts_path(:request_type => 'Show'), remote: true, class:"post-link show-comments" %>
        <%= link_to "Hide Comments", posts_path(:request_type => 'Hide'), remote: true, class:"post-link hide-comments" %>
      <% end %>
      <% if user_signed_in? %>
         <%= link_to 'Add Comment', new_post_comment_path(post), class:'post-link add-comment', remote: true %>
        <% if current_user.admin %>
          <%= link_to 'Edit Post', edit_post_path(post), class:'post-link' %>
        <% end %>
      <% end %>
    </div>
    <div class="comment-form well">
    </div>
      <% if post.comments.any? %>
        <div class="comments">
          <% post.comments.each do |comment| %>
            <div class="comment well">
              <% user = User.find(comment.author_id) %>
              <% if user.image %>
                <div class="comment-image-div">
                  <img class="profile comment-image" src="<%=user.image%>" />
                </div>
              <% end %>
              <div class="comment-header">
                <%=comment.created_at.to_date.strftime('%A')%>
                <%=comment.created_at.to_date.strftime('%B')%>
                <%=comment.created_at.to_date.strftime('%d')%>,
                <%=comment.created_at.to_date.strftime('%Y') %>
              </div>
              <div class="well comment-content">
                <h4>
                  <%= comment.title %>
                </h4>
                <%= comment.content %>
              </div>
              <% user = User.find(comment.author_id) %>
              by <%= link_to user.username, user_path(user), class:'post-link'%><br />
            </div>
          <% end %>

        </div>
        <% end %>
  <% end %>
<% else %>
  <h3>There are no posts yet :( Check back soon :)</h3>
<% end %>

app/views/posts/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
    <div class="row">
      <div class="col-sm-6">
        <div class="post well post-header">
          <%= @post.created_at.to_date.strftime('%A')%>
          <%=@post.created_at.to_date.strftime('%B')%>
          <%=@post.created_at.to_date.strftime('%d')%>,
          <%=@post.created_at.to_date.strftime('%Y') %>
          <div class="post post-updated-at">
            <% if @post.created_at != @post.updated_at %>
              <em>Updated <%= @post.updated_at.to_date.strftime('%A')%>
              <%=@post.updated_at.to_date.strftime('%B')%>
              <%=@post.updated_at.to_date.strftime('%d')%>,
              <%=@post.updated_at.to_date.strftime('%Y') %></em>
            <% end %>
          </div>
          <h3><%= @post.title %></h3>
          <div class="well post-content">
            <%= @post.content %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <h2>Edit Post</h2>
        <%= render 'form', :object => @post%>
      </div>
    </div>
  <% else %>
    <h5>Permission Denied, sorry!</h5>
  <% end %>
<% else %>
    <h5> Please Login. </h5>
<% end %>

app/views/posts/hide.js.erb
$('.comments').hide();
$('.show-comments').show();
$('.hide-comments').hide();

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
  <div class="row">
    <div class=" well col-sm-12 secondary-nav edit-delete-skill">
      <%= link_to 'Add Post', new_post_path(@post) %>
    </div>
  </div>
  <% end %>
<% end %>
<div class="comment-success">
</div>
<div class="posts">
  <%= render 'post_list' %>
</div>

app/views/posts/new.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
    <div class="row">
      <div class="col-sm-6">
        <h2>New Post</h2>
        <h5>Add a post to your blog!</h5>

      </div>
      <div class="col-sm-6">
        <%= render 'form', :object => @post%>
      </div>
    </div>
  <% else %>
    <h5>Permission Denied, sorry!</h5>
  <% end %>
<% else %>
    <h5> Please Login. </h5>
<% end %>

app/views/posts/show.js.erb
$('.comments').show();
$('.show-comments').hide();
$('.hide-comments').show();