config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'skills#index'

  resources :skills do
    resources :projects
  end

  resources :projects, only:[:index]
  resources :users
  resources :posts do
    resources :comments
  end

  resources :references
  resources :recommendations

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioTemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Home', root_path, class: "navbar-brand"  %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav special-color">
            <li><%= link_to 'Blog', posts_path %></li>
            <% if user_signed_in? %>
              <% if current_user.admin %>
                  <li><%= link_to 'Add Skills', new_skill_path%></li>
              <% end %>
            <% end %>
          </ul>


          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right special-color">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username %> <span class="caret"></span>
                </a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Edit account", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to "User Profile", user_path(current_user) %></li>
              </ul>
            </li>
          </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  <div class='container'>
        <%= flash[:alert] %>
      <%= yield %>
  </div>
</body>
</html>